name: build-kotlin

on:
  push:
    paths-ignore:
      - '**.md'

  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    uses: .github/workflows/execute-build-kotlin.yaml
    with:
      allow-github-actor-bots: false
    secrets: inherit
